name: push to github page

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install
      run: |
        npm install
    - name: hexo g
      run: |
        node_modules/hexo/bin/hexo g
    - name: Deploy
      env:
        ACTION_DEPLOY_KEY: ${{ secrets.blog }}
      run: |
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa # 配置秘钥
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        node_modules/hexo/bin/hexo d